package site.hellooo.commons.idgenerator;

import org.junit.Test;

import java.util.HashSet;
import java.util.Set;

public class SnowflakeWorkerTest {
    @Test
    public void generating100000TimesAndUnique() {
        SnowflakeWorker snowflakeWorker = new SnowflakeWorker.SnowflakeWorkerBuilder()
                .dataCenterId(1)
                .machineId(21)
                .build();

        long start = System.currentTimeMillis();
        Set<Long> idSet = new HashSet<>();
        for (int i = 0; i < 100000; i++) {
            long id = snowflakeWorker.nextId();
            if (idSet.contains(id)) {
                System.out.println("num: " + idSet.size());
                System.out.println(id);
                throw new RuntimeException("id generated by snowflake duplicated");
            } else {
                idSet.add(id);
            }
        }
        long timing = System.currentTimeMillis() - start;
        System.out.println("computed num: " + idSet.size() + " timing: " + timing);
    }
}
